# Generated by Django 6.0.4 on 2026-06-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eb_event_id',
            field=models.CharField(blank=True, default='', help_text='Eventbrite numeric Event ID — يفعّل زر شراء التذكرة (Embedded Checkout)', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='slido_code',
            field=models.CharField(blank=True, default='', help_text='Slido event code/hash — يفعّل صفحة التفاعل المباشر مع الحضور', max_length=50),
        ),
    ]
