services:
  - type: web
    name: proevent
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    healthCheckPath: /en/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: proevent-db
          property: connectionString

databases:
  - name: proevent-db
    plan: free
    region: frankfurt
