# Generated by Django 6.0.4 on 2026-06-10 01:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'أساسي'), ('pro', 'احترافي'), ('vip', 'VIP')], max_length=50, unique=True, verbose_name='اسم الباقة')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160, verbose_name='وصف مختصر')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الشهري')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, help_text='عادةً بخصم 20% عن (الشهري × 12)', max_digits=10, verbose_name='السعر السنوي')),
                ('max_events', models.PositiveIntegerField(default=1, verbose_name='عدد الفعاليات المسموح بيها')),
                ('max_attendees', models.PositiveIntegerField(default=100, verbose_name='عدد الحضور المسموح بيه')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='نسبة العمولة على التذاكر %')),
                ('features', models.JSONField(blank=True, default=list, help_text='قائمة نصية، كل عنصر ميزة. مثال: ["دعم فني", "صفحة فعالية مخصّصة"]', verbose_name='المميزات')),
                ('has_slido', models.BooleanField(default=False, verbose_name='تتضمّن Slido؟')),
                ('has_reports', models.BooleanField(default=False, verbose_name='تتضمّن تقارير؟')),
                ('is_popular', models.BooleanField(default=False, verbose_name='الأكثر طلبًا (مميّزة)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة أو المنظّم')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ بداية العقد')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العقد')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة العقد')),
                ('payment_method', models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي')], default='monthly', max_length=10, verbose_name='طريقة الدفع')),
                ('payment_status', models.CharField(choices=[('paid', 'مدفوع'), ('unpaid', 'غير مدفوع')], default='unpaid', max_length=10, verbose_name='حالة الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='subscriptions.package', verbose_name='الباقة المختارة')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم الفاتورة')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('issued_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الفاتورة')),
                ('status', models.CharField(choices=[('paid', 'مدفوعة'), ('unpaid', 'غير مدفوعة')], default='unpaid', max_length=10, verbose_name='حالة الدفع')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='ملف PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issued_date', '-id'],
            },
        ),
    ]
